#!/usr/bin/python3

import sys
import wsl

if __name__ == '__main__':
    args = sys.argv[1:]
    schemafile = None
    if len(args) >= 2 and args[0] == '--schema-file':
        schemafile = args[1]
        args = args[2:]
    if args:
        print('Unconsumed arguments', args, file=sys.stderr)
        sys.exit(1)
    if schemafile:
        with open(schemafile, 'rb') as f:
            sch = f.read()
    else:
        sch = None
    schema, tables = wsl.parse_db(dblines=sys.stdin, schemastr=sch, domain_parsers=None)
    problems = wsl.check_integrity(schema, tables)
    if problems:
        for x in problems:
            print('Integrity error:', x)
    else:
        pass
        #for line in wsl.format_db(schema, tables, inline_schema=True):
        #    print(line, end='')
